# 3 node Qdrant cluster
# Observability with Prometheus and Grafana
#
# Access points:
# - Qdrant dashboard: http://localhost:6333/dashboard#/welcome
# - Grafana: http://localhost:3000/dashboard/db/qdrant-dashboard
# - Prometheus: http://localhost:9090/

services:
  qdrant_node1:
    image: qdrant/qdrant:latest
    container_name: qdrant_node1
    ports:
      - "6333:6333"     # REST API
      - "6334:6334"     # gRPC
    environment:
      QDRANT__CLUSTER__ENABLED: "true"
      QDRANT__LOG_LEVEL: "DEBUG"
    volumes:
      - ${PWD}/.storage/qdrant_node1:/qdrant/storage
    command: "./qdrant --uri http://qdrant_node1:6335"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/healthz"]
      interval: 10s
      timeout: 5s
      retries: 5

  qdrant_node2:
    image: qdrant/qdrant:latest
    container_name: qdrant_node2
    depends_on:
      - qdrant_node1
    ports:
      - "7333:6333"
      - "7334:6334"
    environment:
      QDRANT__CLUSTER__ENABLED: "true"
      QDRANT__LOG_LEVEL: "DEBUG"
    volumes:
      - ${PWD}/.storage/qdrant_node2:/qdrant/storage
    command: "./qdrant --bootstrap http://qdrant_node1:6335 --uri http://qdrant_node2:6335"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/healthz"]
      interval: 10s
      timeout: 5s
      retries: 5

  qdrant_node3:
    image: qdrant/qdrant:latest
    container_name: qdrant_node3
    depends_on:
      - qdrant_node1
    ports:
      - "8333:6333"
      - "8334:6334"
    environment:
      QDRANT__CLUSTER__ENABLED: "true"
      QDRANT__LOG_LEVEL: "DEBUG"
    volumes:
      - ${PWD}/.storage/qdrant_node3:/qdrant/storage
    command: "./qdrant --bootstrap http://qdrant_node1:6335 --uri http://qdrant_node3:6335"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/healthz"]
      interval: 10s
      timeout: 5s
      retries: 5

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    depends_on:
      - qdrant_node1
      - qdrant_node2
      - qdrant_node3
    volumes:
      - ${PWD}/config/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: 'admin'
      GF_SECURITY_ADMIN_PASSWORD: 'admin'
      GF_USERS_ALLOW_SIGN_UP: 'true'
    volumes:
      - ${PWD}/.storage/grafana:/var/lib/grafana
      - ${PWD}/config/grafana.json:/etc/grafana/provisioning/dashboards/qdrant-dashboard.json
      - ${PWD}/config/grafana-dashboard.yaml:/etc/grafana/provisioning/dashboards/grafana-dashboard.yaml
      - ${PWD}/config/grafana-prometheus.yaml:/etc/grafana/provisioning/datasources/prometheus.yaml
    depends_on:
      - prometheus